### ISSUE TITLE
[Anki 23.10 beta 6] Qt.AlignmentFlag.AlignTop

### ISSUE THREAD

**Issue by khonkhortisan** [rroessler1/speech-to-text#14]
> The Qt5 compatibility code is now off by default, which may break some add-ons that haven't been updated to support Qt6 in the last 2 years. If you find any have broken, please report the issues to the add-on author, and start Anki after setting the env var ENABLE_QT5_COMPAT to 1 to temporarily restore the compatibility code.

```py
Error 
Se ha producido un error. Por favor inicia la Anki manteniendo presionadas ples teclas Mayús y la flecha hacia abajo, lo que desactivará temporalmente los extensiones que tienes instaladas. 
Si este error persiste sólo cuando tienes las extensiones activadas, utiliza Herramientas > Menú de Extensiones para deshabilitar alguna extensión y reinicia el Anki, repitiendo este proceso hasta que descubras qué extensión en concreto es la que causa el problema 
Cuando hayas descubierto la extensión que causaba el problema, por favor informa de esto a [sitio de soporte de extensiones](https://forums.ankiweb.net/c/add-ons/11). 
Información de depuración:
Anki 23.10 (72e57456) Python 3.9.15 Qt 6.5.2 PyQt 6.5.2
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-17 07:32:42
Complementos posiblemente implicados: ⁨speech-to-text⁩

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\speech-to-text\__init__.py", line 43, in settings_dialog
    SettingsDialog(app_settings, stt_provider, mw).show()
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\speech-to-text\__init__.py", line 250, in __init__
    layout.setAlignment(Qt.AlignTop)
AttributeError: type object 'Qt' has no attribute 'AlignTop'
```
fix:
\_\_init\_\_.py
```py
try:
    from PyQt6 import QtWidgets
except ImportError:
    from PyQt5 import QtWidgets

            #layout.setAlignment(Qt.AlignTop)
            layout.setAlignment(Qt.AlignmentFlag.AlignTop)

        #buttons = QDialogButtonBox.Ok | QDialogButtonBox.Cancel
        buttons = QDialogButtonBox.StandardButton.Ok | QDialogButtonBox.StandardButton.Cancel

        #hr.setFrameStyle(QFrame.HLine | QFrame.Sunken)
        hr.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        hr.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        hr.setLayout(QVBoxLayout())
        hr2 = QFrame()
        #hr2.setFrameStyle(QFrame.HLine | QFrame.Sunken)
        hr2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        hr2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
```

**Comment by rroessler1** [comment]
Thanks!  I hadn't worked on this for a while, but I fixed it modeled off of your above code.
