### ISSUE TITLE
new issue?

### ISSUE THREAD

**Issue by b-money-salv** [rroessler1/speech-to-text#3]
hi, thanks again for updating the addon, I've attempted to try the pronounce function and encounter this error:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.42 (8eebfe18) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-03-30 10:04:48

Caught exception:
Traceback (most recent call last):
  File "aqt\taskman.py", line 88, in _on_closures_pending
  File "aqt\taskman.py", line 59, in <lambda>
  File "aqt\sound.py", line 600, in and_then
  File "aqt\sound.py", line 522, in stop
  File "aqt\sound.py", line 795, in after_record
  File "C:\Users\curti\AppData\Roaming\Anki2\addons21\673333980\__init__.py", line 76, in after_record
    tts_result = rest_request(recorded_voice, api_key, language_code)
  File "C:\Users\curti\AppData\Roaming\Anki2\addons21\673333980\__init__.py", line 107, in rest_request
    r.raise_for_status()
  File "requests\models.py", line 943, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://speech.googleapis.com/v1/speech:recognize?key=AIzaSy...........................................................................

I followed your instructions & have a google speech to text API free trial code, this came up immediately after recording a word to answer a card. hopefully this is a simple issue?

Thanks again!

**Comment by rroessler1** [comment]
A 403 means your key is invalid or not properly set up, so unfortunately I think this is a problem specific to your key, I don't think I can help.

How did you generate the free trial code?

Following the instructions on the addon page should work.

**Comment by b-money-salv** [comment]
Ok thanks for this, I went through the instructions again and its working perfectly now. This is great. Would you mind if I email you directly? I’m wanting to setup a specific method to go through my decks and I’m sure you’ll have a better idea than me as to how to tackle it, based on what you’ve made here? Thanks again for all of your help, I’m very new to this and really appreciate the help   From: rroessler1Sent: Tuesday, 30 March 2021 10:40 PMTo: rroessler1/speech-to-textCc: b-money-salv; AuthorSubject: Re: [rroessler1/speech-to-text] new issue? (#3) A 403 means your key is invalid or not properly set up, so unfortunately I think this is a problem specific to your key, I don't think I can help.How did you generate the free trial code?Following the instructions on the addon page should work.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rroessler1** [comment]
Awesome, glad to hear it's working!

I'm truly not that knowledgeable about the best way to set up decks and such (I just like developing addons) but I can try and see.  You can email me: ross@languagelearningflashcards.com
