### ISSUE TITLE
403 Client Forbidden

### ISSUE THREAD

**Issue by rroessler1** [rroessler1/speech-to-text#8]
Please help me. In my case, this error appeared: Erro Ocorreu um erro. Por favor, inicie o Anki enquanto segura a tecla shift, isto vai desabilitar temporariamente as extensões que você instalou. Se o problema ocorrer somente quando as extensões são habilitadas, use o Ferramentas > Extensões para desabilitar algumas extensões e reinicie o Anki, repetindo até descobrir a extensão que está causando o problema. Quando você descobrir a extensão que está causando o problema, por favor reporte o problema em site de suporte de extensão. Informações de Depuração: Anki 2.1.46 (94913ec2) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2 Platform: Windows 10 Flags: frz=True ao=True sv=2 Add-ons, last update check: 2021-08-20 02:01:35 Caught exception: Traceback (most recent call last): File "aqt\taskman.py", line 101, in _on_closures_pending File "aqt\taskman.py", line 71, in <lambda> File "aqt\sound.py", line 605, in and_then File "aqt\sound.py", line 527, in stop File "aqt\sound.py", line 800, in after_record File "C:\Users\Affon\AppData\Roaming\Anki2\addons21\673333980\__init__.py", line 74, in after_record tts_result = stt_client.get_stt_results(recorded_voice) File "C:\Users\Affon\AppData\Roaming\Anki2\addons21\673333980\sttclients.py", line 107, in get_stt_results r.raise_for_status() File "requests\models.py", line 943, in raise_for_status requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://speech.googleapis.com/v1/speech:recognize?key=xxxxxxxxxxxxxxxxxxxxx

**Comment by laihuutoan** [comment]
@rroessler1
You may not have enabled STT API. Go here to enable it and check the result.
https://console.cloud.google.com/speech/overview?walkthrough_id=speech-to-text__speech-studio-transcriptions
