### ISSUE TITLE
Replaying audio not working

### ISSUE THREAD

**Issue by itsupera** [rroessler1/speech-to-text#9]
If I try to replay the audio after using the plugin to record it, it fails with the following error.
I've installed the add-on from source and not from Ankiweb by the way.

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.1 Qt 5.15.1 PyQt 5.15.1
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-12-22 16:07:43

Caught exception:
Traceback (most recent call last):
  File "decorator.py", line 231, in fun
  File "decorator.py", line 203, in fix
  File "inspect.py", line 3025, in bind
  File "inspect.py", line 2946, in _bind
TypeError: too many positional arguments
```

**Comment by rroessler1** [comment]
Thanks for the report.  Looks like maybe an internal API changed?  I'm on vacation until next week, then can have a look.

**Comment by rroessler1** [comment]
Apologies that I'm looking at this a month later than I said I would, but looking at it now.

I think I don't understand exactly what's happening.  Are you trying to replay the audio on the card, or your own recorded voice?  If it's your own recorded voice, how are you replaying that?

**Comment by itsupera** [comment]
No worries and apologies for the unclear description: it happens when a replay my own recorded voice.

It is very likely due to changes in the API, as I had other issues with many extensions when upgrading from 2.1.35 to 2.1.49.
